name: Docker

on:
  push:
    branches:    
      # Push events on master branch
      - master  
    tags:        
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ludat/patova-proxy
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true # optional
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true # optional
        # Comma-delimited list of build-time variables
        # build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        # cache_froms: # optional
        # Comma-delimited list of labels to add to the built image
        # labels: # optional
        # Adds labels with git repository information to the built image
        add_git_labels: true # optional
        # Whether to push the image
        push: true # optional, default is true
